import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/layout/sidebar";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";

import "primereact/resources/themes/lara-light-blue/theme.css";
import "primereact/resources/primereact.min.css";

import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-light-indigo/theme.css"; // ou outro tema
import "primereact/resources/primereact.min.css";
import SectionLayout from "@/components/layout/sectionLayout";
import { MockDataProvider } from "@/context/MockDataContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased relative min-h-screen`}
      >
        <PrimeReactProvider>
          <MockDataProvider>
            <div className="w-[260px] h-full fixed">
              <Sidebar />
            </div>
            <SectionLayout>{children}</SectionLayout>
          </MockDataProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
